name: e_class
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  dio: ^5.2.1
  flutter:
    sdk: flutter
  mongo_dart: ^0.9.1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

  assets:
    - assets/images/
  
  fonts:
    - family: Gotu
      fonts:
        - asset: assets\fonts\Gotu-Regular.ttf
  uses-material-design: true



flutter_icons:

  image_path: "assets/images/logo.png"
  android: true
  ios: true
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "
    theme_color: "
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/images/logo.png"